---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +
  geom_point() +
  theme_void() +
  labs(title = "QUIN was here") +
  theme_bw()
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter() +
  theme_light() +
  labs(title = "Kelsie was here")
```

## PART B: Make problems

```{r break-it-1}
hi_price <- diamonds %>% 
  filter(price > 1000)

ggplot(data = hi_price, aes(x = carat, y = price, color = cut)) +
  geom_point() +
  theme_void() +
  labs(title = "QUIN was here") +
  theme_minimal()
```

```{r break-it-2}

```

## END Discussion 3
